# Makefile for load balancer project

CXX = g++
CXXFLAGS = -Wall -Werror -std=c++11 -g -ldl
LIBS = thread.o libinterrupt.a

lbs: lb.cc
	$(CXX) $(CXXFLAGS) -o $@ lb.cc $(LIBS)

clean:
	rm -rf lb lb.dSYM